name: hidato
version: 1.0.0.0
github: 'dfg-98/hidato'
license: BSD3
author: 'Darío Fragas'
maintainer: 'dariofg98@gmail.com'
copyright: '2022 Dario Fragas'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/dfg-98/hidato#readme>

dependencies:
  - base >= 4.7 && < 5
  - split
  - random
  - containers
  - optparse-applicative

library:
  source-dirs: src

executables:
  Solver:
    main: Main.hs
    source-dirs: app/Solver
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hidato
      - random
      - split
      - optparse-applicative
  Generator:
    main: Main.hs
    source-dirs: app/Generator
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hidato
      - random
      - split
      - optparse-applicative
